### ISSUE TITLE
Scrim descriptions should convert new lines

### ISSUE THREAD

**Issue by everyplace** [CooperUnion/endofyearshow2021#20]
See the most recent piece [here](https://endofyearshow2021.cooper.edu/student/maya-van-bael) titled "green light." The description has lots of lime breaks in it as stored, but are stripped out as rendered. We should either convert line breaks to br's, or split on them and wrap each paragraph properly in p tags.

**Comment by heatloss** [comment]
Turns out there’s a CSS property that fixes this: `white-space: break-spaces`, which I had never heard of before now.

**Comment by everyplace** [comment]
Looks like you could replace line 77: 

`<p v-if="meta.description" class="description" v-html="meta.description"></p>`

To something like: 

`<div v-if="meta.description" class="description" v-html="parseLineBreaks(meta.description)"></div>`

And then implement a parseLineBreaks function, something along the lines of: 

```javascript
const parseLineBreaks = (line) => {
 return line.split('\n').map(p=>`<p>${p}</p>`)
}
```
