### ISSUE TITLE
Investigate why Ruth’s video doesn’t load

### ISSUE THREAD

**Issue by everyplace** [CooperUnion/endofyearshow2021#22]
https://endofyearshow2021.cooper.edu/student/ruth-plumb the first video "Forest Response" doesn't load.

**Comment by heatloss** [comment]
According to Vimeo, this video appears to have timed out during the uploading process:
https://vimeo.com/manage/553950347/general

**Comment by everyplace** [comment]
Good catch. I'll email Ruth.
